name: hello
description: Hello kubernetes.

version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  shelf: ^1.3.2
  shelf_router: ^1.1.3

dev_dependencies:
  http: ^0.13.5
  lints: ^2.0.0
  test: ^1.21.5
