apiVersion: v1
kind: Service
metadata:
  name: hello-dart-service
spec:
  selector:
    app: hello-dart
  ports:
  - protocol: "TCP"
    port: 5001
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dart
spec:
  selector:
    matchLabels:
      app: hello-dart
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-dart
    spec:
      containers:
      - name: hello-dart
        image: hello-dart:latest
        imagePullPolicy: Never   # use Never for local testing, preventing lookup on remote registry
        ports:
        - containerPort: 5000
